/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2014 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void (*init_proc())(void);
// int printf(const char *format, ...);
// int puts(const char *s);
// int __gmon_start__(void); weak
// int __isoc99_scanf(const char *, ...); weak
void _do_global_dtors_aux();
int frame_dummy();
int give_flag();
int purchase_items();
int __cdecl main(int argc, const char **argv, const char **envp);
int *_libc_csu_init();
void _i686_get_pc_thunk_bx();
void (*_do_global_ctors_aux())(void);
void term_proc();

//-------------------------------------------------------------------------
// Data declarations

int _CTOR_LIST__ = 4294967295; // weak
int _DTOR_LIST__[] = { 4294967295 }; // weak
_UNKNOWN _DTOR_END__; // weak
int _JCR_LIST__ = 0; // weak
char completed_6159; // weak
int dtor_idx_6161; // weak
// extern _UNKNOWN _gmon_start__; weak


//----- (08048314) --------------------------------------------------------
void (*init_proc())(void)
{
  if ( &_gmon_start__ )
    __gmon_start__();
  frame_dummy();
  return _do_global_ctors_aux();
}
// 8048380: using guessed type int __gmon_start__(void);

//----- (080483B0) --------------------------------------------------------
#error "80483B3: positive sp value has been found (funcsize=2)"

//----- (080483E0) --------------------------------------------------------
void _do_global_dtors_aux()
{
  int v0; // eax@2
  int i; // ebx@2

  if ( !completed_6159 )
  {
    v0 = dtor_idx_6161;
    for ( i = ((&_DTOR_END__ - (_UNKNOWN *)_DTOR_LIST__) >> 2) - 1; dtor_idx_6161 < (unsigned int)i; v0 = dtor_idx_6161 )
    {
      dtor_idx_6161 = v0 + 1;
      ((void (*)(void))_DTOR_LIST__[v0 + 1])();
    }
    completed_6159 = 1;
  }
}
// 8049F1C: using guessed type int _DTOR_LIST__[];
// 804A01C: using guessed type char completed_6159;
// 804A020: using guessed type int dtor_idx_6161;

//----- (08048440) --------------------------------------------------------
int frame_dummy()
{
  int result; // eax@1

  result = _JCR_LIST__;
  if ( _JCR_LIST__ )
    result = 0;
  return result;
}
// 8049F24: using guessed type int _JCR_LIST__;

//----- (08048464) --------------------------------------------------------
int give_flag()
{
  return puts("{flag}");
}

//----- (08048478) --------------------------------------------------------
int purchase_items()
{
  int result; // eax@10
  int v1; // [sp+14h] [bp-14h]@1
  int v2; // [sp+18h] [bp-10h]@1
  int v3; // [sp+1Ch] [bp-Ch]@2

  puts("Here is the list of items we sell at this store.");
  puts("Each item has an associated I.D. number and cost. Please concatenate the I.D. numbers of all the items you would like to purchase and input that.");
  puts("I.D.    Name       Cost");
  puts("1     Potatoes     $1.00");
  puts("2     Trash Can    $10.00");
  puts("3     Baseball     $5.00");
  puts("4     Cell Phone   $100.00");
  puts("5     Laptop       $500.00");
  puts("6     Fireworks    $20.00");
  puts("7     Tomatoes     $7.00");
  v1 = 0;
  v2 = 0;
  __isoc99_scanf("%d", &v1);
  while ( 2 )
  {
    result = v1;
    if ( v1 > 0 )
    {
      v3 = v1 % 10;
      v1 /= 10;
      switch ( v3 )
      {
        case 1:
          ++v2;
          continue;
        case 2:
          v2 += 10;
          continue;
        case 3:
          v2 += 5;
          continue;
        case 4:
          v2 += 100;
          continue;
        case 5:
          v2 += 500;
          continue;
        case 6:
          v2 += 20;
          continue;
        case 7:
          v2 += 7;
          continue;
        default:
          result = printf("Invalid option: %d\n", v3);
          break;
      }
    }
    else if ( v2 == 1337 )
    {
      result = give_flag();
    }
    break;
  }
  return result;
}
// 80483A0: using guessed type int __isoc99_scanf(const char *, ...);

//----- (080485E4) --------------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  puts("Welcome to the cash register at Keith's Supermarket!");
  purchase_items();
  return 0;
}

//----- (08048610) --------------------------------------------------------
int *_libc_csu_init()
{
  init_proc();
  return &_CTOR_LIST__;
}
// 8049F14: using guessed type int _CTOR_LIST__;

//----- (08048682) --------------------------------------------------------
void _i686_get_pc_thunk_bx()
{
  ;
}

//----- (08048690) --------------------------------------------------------
void (*_do_global_ctors_aux())(void)
{
  void (*result)(void); // eax@1
  int *v1; // ebx@2

  result = (void (*)(void))_CTOR_LIST__;
  if ( _CTOR_LIST__ != -1 )
  {
    v1 = &_CTOR_LIST__;
    do
    {
      --v1;
      result();
      result = (void (*)(void))*v1;
    }
    while ( *v1 != -1 );
  }
  return result;
}
// 8049F14: using guessed type int _CTOR_LIST__;

//----- (080486BC) --------------------------------------------------------
void term_proc()
{
  _do_global_dtors_aux();
}

#error "There were 1 decompilation failure(s) on 11 function(s)"
